### ISSUE TITLE
Share Release on Social

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#183]

**Comment by rubengc** [comment]
I could recomend you promote some hastags referencing Voxel Shop on twitter as: #VoxelShop (of course) #madewithvoxelshop #VoxelShopTip (use this to talk about avanced or useful features)

Are you thinking on make a official profile for voxel shop instead of use your own?

Some daily/weekly challenges could be awesome to promote the use of Voxel Shop

**Comment by simlu** [comment]
Lots of good ideas. I prefer things that require little time... Let's see how the tutorial ppl are being received!

**Comment by simlu** [comment]
Posted release notes on twitter.
