### ISSUE TITLE
Create native Installer (ExcelsiorJET)

### ISSUE THREAD

**Issue by simlu** [simlu/voxelshop#184]

**Comment by simlu** [comment]
I'll do this once the java release is live for a while - in case there are any bugs we want to fix.

**Comment by simlu** [comment]
Working on this now...

**Comment by funabab** [comment]
I don't see any real reason behind the native installers apart from the fact that it does not require java installed. I know the pain it takes to build native installers for different OS which IMO is a big stress for a little reward. Since java is very popular (if not a requirement for every PC :D ) i don't think it's helpful to maintain native installers, moreover the java version is much much faster than native installer.

**Comment by funabab** [comment]
But if you insist on maintaining a native installer maybe you should document the process. I can help with  linux (and maybe windows) builds.

**Comment by simlu** [comment]
I'm using [ExcelsiorJet](https://www.excelsiorjet.com/) and VirtualBox, so it's not too much of a pain. I agree that the process should be documented. However I'm planning to integrate it with the build process... then every time something gets pushed to master a release is generated automatically.

**Comment by simlu** [comment]
Done
